# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Phil Nash
email: philnash@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Phil Nash is a developer, speaker, blogger and occasionally a brewer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://philna.sh" # the base hostname & protocol for your site
twitter_username: philnash
github_username:  philnash

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/
paginate_path: /blog/page/:num
paginate: 10
gems:
  - jekyll-paginate
  - jekyll-assets

assets:
  prefix: /assets
  css_compressor: sass
  sources:
    - _assets/css
    - _assets/images

defaults:
  -
    scope:
      path: ""
      type: "posts" # previously `page` in Jekyll 2.2.
    values:
      author: "Phil Nash"
