# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Phil Nash
email: philnash@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Phil Nash is a developer, speaker, blogger and occasionally a brewer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://philna.sh" # the base hostname & protocol for your site
twitter_username: philnash
twitter_user_id: 9152632
github_username:  philnash
timezone: Europe/London
sw_cache_version: 1

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/
paginate_path: /blog/page/:num
paginate: 10
gems:
  - jekyll-paginate
  - jekyll-assets
  - liquid-md5
  - jekyll-sitemap
  - uglifier

assets:
  prefix: /assets
  css_compressor: sass
  js_compressor: uglifier
  sources:
    - _assets/css
    - _assets/images
    - _assets/js
    - _assets/fonts
  digest: true
  precompile: true


defaults:
  -
    scope:
      path: ""
      type: "posts" # previously `page` in Jekyll 2.2.
    values:
      author: "Phil Nash"
      show_image: true
