# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Phil Nash
email: philnash@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Phil Nash is a developer, speaker, blogger and occasionally a brewer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://philna.sh" # the base hostname & protocol for your site
domain: "philna.sh"
twitter_username: philnash
twitter_user_id: 9152632
github_username:  philnash
web_monetization: $ilp.gatehub.net/532270252
timezone: Europe/London
sw_cache_version: 2

# Build settings
exclude: [deploy, bower_components]
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/
paginate_path: /blog/page/:num/
paginate: 10
plugins:
  - jekyll-paginate
  - jekyll-assets
  - liquid-md5
  - jekyll-sitemap
  - uglifier
  - jekyll-zopfli
  - jekyll-brotli

assets:
  prefix: /assets
  css_compressor: sass
  js_compressor: uglifier
  digest: true
  precompile: []


defaults:
  -
    scope:
      path: ""
      type: "posts" # previously `page` in Jekyll 2.2.
    values:
      author: "Phil Nash"
      author_url: "https://philna.sh"
      show_image: true
